# Generated by Django 4.2.4 on 2023-11-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0002_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="Blog", max_length=256),
        ),
    ]
