# Generated by Django 4.2.4 on 2023-11-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0004_post_post_date_alter_post_title_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="uncategorized", max_length=256),
        ),
    ]
