# Generated by Django 4.2.4 on 2023-11-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0007_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_resume",
            field=models.CharField(
                default=models.CharField(max_length=256), max_length=256
            ),
        ),
    ]
