# Generated by Django 4.2.4 on 2023-11-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0009_alter_post_post_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_resume",
            field=models.CharField(max_length=256),
        ),
    ]
