# Generated by Django 4.2.4 on 2023-11-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0010_alter_post_post_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
