# Generated by Django 4.2.4 on 2023-11-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0012_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="facebook_url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
    ]
