# Generated by Django 4.2.4 on 2023-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theblog", "0013_userprofile_facebook_url_userprofile_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
